import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ApiService } from '../../services/api.service';
import { DocumentService } from '../../services/document.service';
@Component({ standalone: true, imports: [CommonModule, FormsModule], template: `
  <section class="heading"><div><p class="eyebrow">Authenticated endpoint management</p><h1>API Explorer</h1><p>All operations use the global <code>X-API-Key</code>. Supervisor-only approval actions require the supervisor test key.</p></div></section>
  <div class="tabs"><button (click)="tab.set('search')" [class.selected]="tab()==='search'">Search & Documents</button><button (click)="tab.set('sessions')" [class.selected]="tab()==='sessions'">Sessions & Runs</button><button (click)="tab.set('approvals')" [class.selected]="tab()==='approvals'">Approvals & Traces</button></div>
  <section *ngIf="tab()==='search'" class="grid-two"><article class="panel"><h2>Hybrid search</h2><form (ngSubmit)="search()"><label>Query<input [(ngModel)]="query" name="query" required></label><label>Top K<input [(ngModel)]="topK" name="topK" type="number" min="1" max="100"></label><button>Search</button></form><div *ngFor="let item of searchItems()" class="item"><strong>{{item.title}}</strong><p>{{item.content}}</p><small>{{item.sourceReference}} · document {{item.documentId}}</small></div></article><article class="panel"><h2>Document details</h2><form (ngSubmit)="getDocument()"><label>Document ID<input [(ngModel)]="documentId" name="documentId" required></label><button>Get document</button></form><pre>{{ result() }}</pre></article></section>
  <section *ngIf="tab()==='sessions'" class="grid-two"><article class="panel"><h2>Sessions</h2><button (click)="loadSessions()">List sessions</button><div *ngFor="let s of sessions()" class="item"><strong>{{s.title}}</strong><small>{{s.sessionId}} · {{s.status}}</small><button (click)="getMessages(s.sessionId)">Messages</button></div><h2>Create session</h2><form (ngSubmit)="createSession()"><input [(ngModel)]="sessionTitle" name="sessionTitle" placeholder="Title"><button>Create</button></form></article><article class="panel"><h2>Runs</h2><button (click)="loadRuns()">List runs</button><div *ngFor="let run of runs()" class="item"><strong>{{run.status}} · {{run.patternName}}</strong><small>{{run.runId}} · {{run.durationMs}} ms</small><button (click)="getRun(run.runId)">Details</button></div></article></section>
  <section *ngIf="tab()==='approvals'" class="grid-two"><article class="panel"><h2>Approvals</h2><button (click)="loadApprovals()">List approvals</button><div *ngFor="let approval of approvals()" class="item"><strong>{{approval.proposedAction}}</strong><small>{{approval.requestId}} · {{approval.decision}}</small></div><h3>Supervisor decision / execute</h3><form (ngSubmit)="decide()"><input [(ngModel)]="approvalId" name="approvalId" placeholder="Approval request ID" required><select [(ngModel)]="decision" name="decision"><option>Approved</option><option>Rejected</option><option>Edited</option></select><input [(ngModel)]="comments" name="comments" placeholder="Comments"><textarea [(ngModel)]="editedPayload" name="payload" placeholder="Edited payload"></textarea><button>Submit decision</button></form><button class="danger" (click)="execute()">Execute approved action</button></article><article class="panel"><h2>LLM traces</h2><form (ngSubmit)="loadTraces()"><select [(ngModel)]="traceFilter" name="filter"><option value="runId">Run ID</option><option value="correlationId">Correlation ID</option></select><input [(ngModel)]="traceValue" name="traceValue" required placeholder="Identifier"><button>Load traces</button></form><pre>{{ result() }}</pre></article></section>
  <section class="panel"><h2>Response</h2><pre>{{ result() }}</pre></section>
` })
export class ExplorerComponent {
  private readonly api = inject(ApiService); private readonly docs = inject(DocumentService);
  readonly tab = signal<'search'|'sessions'|'approvals'>('search'); readonly result = signal('Select an action to view a typed API response.'); readonly searchItems = signal<any[]>([]); readonly sessions = signal<any[]>([]); readonly runs = signal<any[]>([]); readonly approvals = signal<any[]>([]);
  query = ''; topK = 5; documentId = ''; sessionTitle = 'Angular session'; approvalId = ''; decision: 'Approved'|'Rejected'|'Edited' = 'Approved'; comments = ''; editedPayload = ''; traceFilter: 'runId'|'correlationId' = 'runId'; traceValue = '';
  private show(value: unknown): void { this.result.set(JSON.stringify(value, null, 2)); } private fail(error: Error): void { this.result.set(error.message); }
  search(): void { this.api.search(this.query, this.topK).subscribe({next:r=>{this.searchItems.set(r.items);this.show(r);},error:e=>this.fail(e)}); } getDocument(): void { this.docs.get(this.documentId).subscribe({next:x=>this.show(x),error:e=>this.fail(e)}); }
  loadSessions(): void { this.api.sessions().subscribe({next:x=>{this.sessions.set(x);this.show(x);},error:e=>this.fail(e)}); } createSession(): void { this.api.createSession({title:this.sessionTitle}).subscribe({next:x=>this.show(x),error:e=>this.fail(e)}); } getMessages(id:string):void { this.api.sessionMessages(id).subscribe({next:x=>this.show(x),error:e=>this.fail(e)}); }
  loadRuns():void { this.api.runs().subscribe({next:x=>{this.runs.set(x);this.show(x);},error:e=>this.fail(e)}); } getRun(id:string):void { this.api.run(id).subscribe({next:x=>this.show(x),error:e=>this.fail(e)}); }
  loadApprovals():void { this.api.approvals().subscribe({next:x=>{this.approvals.set(x);this.show(x);},error:e=>this.fail(e)}); } decide():void { this.api.decide(this.approvalId,{decision:this.decision,comments:this.comments||undefined,editedPayload:this.editedPayload||undefined}).subscribe({next:x=>this.show(x),error:e=>this.fail(e)}); } execute():void { this.api.execute(this.approvalId).subscribe({next:x=>this.show(x),error:e=>this.fail(e)}); } loadTraces():void { this.api.traces({[this.traceFilter]:this.traceValue}).subscribe({next:x=>this.show(x),error:e=>this.fail(e)}); }
}
