import { Component, ElementRef, ViewChild, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Observable } from 'rxjs';
import { ApiService } from '../../services/api.service';
import { CopilotService } from '../../services/copilot.service';
import { DocumentService } from '../../services/document.service';
import { Citation, SessionMessage } from '../../models/api.models';
type ChatEntry = { role: 'user' | 'assistant'; content: string; status?: string; citations?: Citation[] };
@Component({ standalone: true, imports: [CommonModule, FormsModule], template: `
  <section class="heading"><div><p class="eyebrow">Document analysis</p><h1>AI Copilot</h1><p>Answers are produced only from retrieved, tenant-scoped evidence.</p></div><button (click)="newSession()">New session</button></section>
  <div class="grid-two"><section class="panel chat"><div class="chat-header"><strong>{{ sessionId() ? 'Session ' + sessionId() : 'No active session' }}</strong><select [(ngModel)]="mode"><option value="answer">Grounded answer</option><option value="orchestrate">Multi-agent orchestration</option><option value="stream">Stream orchestration</option></select></div><div class="messages"><article *ngFor="let entry of messages()" [class.user]="entry.role === 'user'"><b>{{ entry.role === 'user' ? 'You' : 'Copilot' }}</b><p>{{ entry.content }}</p><small *ngFor="let citation of entry.citations">Source: {{ citation.title }} — {{ citation.sourceReference }}</small></article><p *ngIf="!messages().length" class="muted">Start by uploading a source document, then ask a question.</p></div><form (ngSubmit)="send()"><textarea [(ngModel)]="query" name="query" required maxlength="4000" placeholder="Ask about an uploaded document or government rule…"></textarea><button [disabled]="busy()">{{ busy() ? 'Working…' : 'Send' }}</button></form></section>
  <section class="panel"><h2>Upload source document</h2><p class="muted">The API accepts text JSON, not multipart files. Text-based files are read in this browser and sent as <code>sourceText</code>.</p><label>Title<input [(ngModel)]="title" name="title" required></label><label>Source reference<input [(ngModel)]="sourceReference" name="source" required placeholder="URL or registry identifier"></label><label>File<input #fileInput type="file" accept=".txt,.md,.csv,.json,.xml,.html,text/plain,text/markdown,text/csv,application/json" (change)="selectFile(fileInput)"></label><button (click)="upload()" [disabled]="!file || busy()">Ingest document</button><p class="message-status">{{ uploadStatus() }}</p></section></div>
` })
export class CopilotComponent {
  private readonly api = inject(ApiService); private readonly copilot = inject(CopilotService); private readonly documents = inject(DocumentService);
  @ViewChild('fileInput') fileInput?: ElementRef<HTMLInputElement>;
  readonly messages = signal<ChatEntry[]>([]); readonly sessionId = signal<string | null>(null); readonly busy = signal(false); readonly uploadStatus = signal('');
  query = ''; mode: 'answer' | 'orchestrate' | 'stream' = 'answer'; title = ''; sourceReference = ''; file?: File;
  selectFile(input: HTMLInputElement): void { this.file = input.files?.[0]; this.uploadStatus.set(this.file ? `${this.file.name} ready to ingest.` : ''); }
  newSession(): void { this.api.createSession({ title: 'Angular Copilot session' }).subscribe({ next: s => { this.sessionId.set(s.sessionId); this.messages.set([]); }, error: e => this.uploadStatus.set(e.message) }); }
  private ensureSession(next: (id: string) => void): void { const existing = this.sessionId(); if (existing) { next(existing); return; } this.api.createSession({ title: 'Angular Copilot session' }).subscribe({ next: s => { this.sessionId.set(s.sessionId); next(s.sessionId); }, error: e => this.add('assistant', e.message, 'Error') }); }
  send(): void { const text = this.query.trim(); if (!text || this.busy()) return; this.add('user', text); this.query = ''; this.busy.set(true); if (this.mode === 'stream') { this.copilot.stream({ query: text, sessionId: this.sessionId() ?? undefined }).subscribe({ next: chunk => this.appendStream(chunk), error: e => { this.add('assistant', e.message, 'Error'); this.busy.set(false); }, complete: () => this.busy.set(false) }); return; } this.ensureSession(id => { const call: Observable<any> = this.mode === 'answer' ? this.api.postMessage(id, { content: text, mode: 'answer' }) : this.api.orchestrate({ query: text, sessionId: id }); call.subscribe({ next: (result: any) => { const response = 'content' in result ? result : { content: result.answer ?? result.failureReason ?? result.status, status: result.status, citations: result.citations }; this.add('assistant', response.content, response.status, response.citations); this.busy.set(false); }, error: (e: any) => { this.add('assistant', e.message, 'Error'); this.busy.set(false); } }); }); }
  upload(): void { if (!this.file) return; if (this.file.size > 1_900_000) { this.uploadStatus.set('File exceeds the API request-size limit.'); return; } this.busy.set(true); this.file.text().then(sourceText => this.documents.ingest({ title: this.title, sourceReference: this.sourceReference, sourceText }).subscribe({ next: r => { this.uploadStatus.set(`Ingested ${r.chunkCount} chunks. Document ID: ${r.documentId}`); this.busy.set(false); }, error: e => { this.uploadStatus.set(e.message); this.busy.set(false); } })); }
  private add(role: 'user' | 'assistant', content: string, status?: string, citations?: Citation[]): void { this.messages.update(items => [...items, { role, content, status, citations }]); }
  private appendStream(chunk: unknown): void { const value = typeof chunk === 'string' ? chunk : (chunk as { content?: string; answer?: string; message?: string }).content ?? (chunk as { answer?: string }).answer ?? (chunk as { message?: string }).message ?? ''; const current = this.messages(); const last = current.at(-1); if (last?.role === 'assistant' && last.status === 'Streaming') this.messages.set([...current.slice(0, -1), { ...last, content: last.content + value }]); else this.add('assistant', value || 'Streaming started…', 'Streaming'); }
}
